[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "verilogen"
version = "0.0.1"
dependencies = [
    "click",
    "jinja2",
]

[project.scripts]
verilogen = "verilogen.verilogen:generate"
